server:
    port: 8888
spring:
    thymeleaf:
      cache: false
security:
  user:
    name: tktest
    password: aa123456

welcome:
  message: test1

---
spring:
  profiles: default

welcome:
  message: staging environment

---
spring:
  profiles: prod

welcome:
  message: production environment